Lesson1
ilya-xbsoftware/webix-level2 pull request #1
Opened 2021-04-15 09:00 UTC by ilya-xbsoftware

2021-04-15 09:10 UTC, ekosiy requested changes

2021-04-15 09:10 UTC, ekosiy commented on src/js/components/uiCustome/reusableForm.js
> +    this.refresh();
тут refresh точно нужен?

2021-04-15 09:10 UTC, ekosiy commented on src/js/components/uiCustome/reusableForm.js
> +      if(self.saveAction) {
можешь пожалуйста еще проверять на typeof function?

2021-04-15 09:10 UTC, ekosiy commented on src/js/components/uiCustome/toggleButton.js
> +    config.value = config.states[0],
более гибко было бы получать value в конфиге отдельно, а не брать первое из стэйта. Тогда можно при загрузке сразу указать нужную конфигурацию

2021-04-15 09:10 UTC, ekosiy commented on src/js/components/uiCustome/toggleButton.js
> +    this.$view.className = "off",
мне кажется тут лучше через add делать, а не переписывать все классы
так можно затереть уже существующий

2021-04-15 09:10 UTC, ekosiy commented on src/js/components/uiCustome/toggleButton.js
> +      const lastState = 3;
хардкод в номерах не допустим, лучше брать это из данных, которые приходят

2021-04-15 09:10 UTC, ekosiy commented on src/js/utils/addingZeros.js
> +export default function addingZeros(string) {
зачем тянуть утилиты в новый проект, если они не используются тут пока?

2021-04-15 09:40 UTC, ilya-xbsoftware commented on src/js/utils/addingZeros.js
> +export default function addingZeros(string) {
Это от предыдущего таска. ..забыл удалить.
Исправил !

2021-04-15 09:41 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/reusableForm.js
> +    this.refresh();
он не нужен, так как обнулять ничего не надо .. 
Исправил !

2021-04-15 09:42 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/reusableForm.js
> +      if(self.saveAction) {
да, хорошо. 
Исправил !

2021-04-15 11:38 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/toggleButton.js
> +      const lastState = 3;
понял. 
Исправил !

2021-04-15 11:44 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/toggleButton.js
> +    config.value = config.states[0],
да, точно  !
Разорался. 
Исправил.

2021-04-15 11:44 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/toggleButton.js
> +    config.value = config.states[0],
да, точно ! 
разобрался и исправил !

2021-04-15 12:49 UTC, Zwillinge requested changes

2021-04-15 12:49 UTC, Zwillinge commented on src/js/components/uiCustome/toggleButton.js
> +function setBtnColor(btn){
это не должно быть ф-цией заданной вне виджета. такие вещи надо задавать как приватные методы на объекте. то же самое касается и формы

2021-04-15 12:49 UTC, Zwillinge commented on src/js/components/uiCustome/reusableForm.js
> +    return parameters;
сеттер опционален. если мы не меляем параметры, то его задавать не нужно

2021-04-15 12:49 UTC, Zwillinge commented on src/js/components/uiCustome/reusableForm.js
> +    const self = this;
зачем здесь self, если this доступен внутри клика благорадя `=>`?

2021-04-15 12:49 UTC, Zwillinge commented on src/js/components/uiCustome/reusableForm.js
> +    this.saveAction = config.saveAction;
не нужно свойства из конфига перекидывать на объект. ты в createForm передаешь config, еще бы желательно там его использовать, а не получать с объекта

2021-04-15 12:49 UTC, Zwillinge commented on src/js/components/uiCustome/reusableForm.js
> +        webix.message({type:"success", text:"The form is saved !"})
по ТЗ ф-ции saveAction, cancelAction должны быть записаны в defaults и соответственно оттуда и браться. 
то есть или

// config еще не формирован когда ты аттачишь обработчик
`view:"button", click:config.saveAction || this.defaults.saveAction` 

// config  уже формирован когда  обработчик вызван
`view:"button", click:=>{ this.config.saveAction()}`

2021-04-15 13:13 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/toggleButton.js
> +function setBtnColor(btn){
разобрался. 
встроил методы.

2021-04-15 13:25 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/reusableForm.js
> +    const self = this;
исправил. Дальше должна была быть не стрелочная функция, а  через function().

2021-04-15 13:26 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/reusableForm.js
> +    return parameters;
понял, исправил

2021-04-15 14:23 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/reusableForm.js
> +    this.saveAction = config.saveAction;
Разобрался ! 
Все исправил.

2021-04-15 14:24 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/reusableForm.js
> +        webix.message({type:"success", text:"The form is saved !"})
Разобрал. 
Перенес.

2021-04-15 15:26 UTC, ekosiy approved these changes

2021-04-16 10:12 UTC, Zwillinge commented on src/js/components/uiCustome/reusableForm.js
> +      if(self.saveAction) {
а почему только для save, но не для cancel?

2021-04-16 10:17 UTC, Zwillinge commented on src/js/components/uiCustome/toggleButton.js
> +    this.states = config.states;
как и с формой, не нужно тащить вещи заданные на конфиге, на объект 
у тебя получается никогда не меняется config.state, хотя настройка должна не только задавать начальное состояние, но и отражать текущее. а states, хотя и статичный, всё равно не нужно перекидывать на объект, потому что у тебя одни и те же данные хранятся в двух местах (на view и на view.config). view.config.some доступен из любого метода на чтение и запись

а служебные маркеры вроде this.startState надо делать приватныеми, т.е начинать с `_`

2021-04-16 12:53 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/toggleButton.js
> +    this.states = config.states;
Да, Понял. 
убрал => this.config.value = "Off"

2021-04-16 13:03 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/reusableForm.js
> +      if(self.saveAction) {
конечно нужно ! 
сделал.

2021-04-16 13:29 UTC, Zwillinge commented on src/js/components/uiCustome/toggleButton.js
> +    this.states = config.states;
может не понятно.. нам не надо присваивать вот это this.state, this.states, потому что это уже есть в конфиге и надо оттуа считывать и туда записывать 


а это делаем приватным свойством объекта, оно юзерам не нужно  
this.startState, this.lastState ->this._startState, this._lastState

2021-04-16 13:47 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/toggleButton.js
> +    this.states = config.states;
Ольга, я доделал !

2021-04-16 13:50 UTC, Zwillinge commented on src/js/components/uiCustome/toggleButton.js
> +    this.states = config.states;
а азчем дублировать хранение states? `this._states = config.states;`

2021-04-16 14:08 UTC, ilya-xbsoftware commented on src/js/components/uiCustome/toggleButton.js
> +    this.states = config.states;
Да это тоже как и state ... 
Разобрался, сделал !

2021-04-16 14:28 UTC, Zwillinge approved these changes

2021-04-16 19:49 UTC, merged